#ifndef CARTOGRAPHER_H
#define CARTOGRAPHER_H

/* This file is generated by cbindgen. Do not edit manually. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

/**
 * SVG size threshold in bytes (only ignore if > 2KB)
 */
#define SVG_SIZE_THRESHOLD 2048

/**
 * Free a string returned by any `cartographer_*` function.
 *
 * # Safety
 * `ptr` must be a valid pointer returned by a Cartographer FFI function,
 * and must not have been freed already.
 */
void cartographer_free_string(char *ptr);

/**
 * Scan a project directory and return the full project graph as JSON.
 *
 * Input:  `path` — absolute path to project root (C string)
 * Output: JSON string (must be freed with `cartographer_free_string`)
 *
 * Response shape:
 * ```json
 * {
 *   "ok": true,
 *   "data": {
 *     "nodes": [...],
 *     "edges": [...],
 *     "cycles": [...],
 *     "godModules": [...],
 *     "layerViolations": [...],
 *     "metadata": { ... }
 *   }
 * }
 * ```
 */
char *cartographer_map_project(const char *path);

/**
 * Return the architectural health score for a project.
 *
 * Response shape:
 * ```json
 * {
 *   "ok": true,
 *   "data": {
 *     "healthScore": 72.5,
 *     "totalFiles": 150,
 *     "totalEdges": 320,
 *     "bridgeCount": 3,
 *     "cycleCount": 1,
 *     "godModuleCount": 0,
 *     "layerViolationCount": 2
 *   }
 * }
 * ```
 */
char *cartographer_health(const char *path);

/**
 * Check a project against a `layers.toml` config file.
 *
 * Inputs:
 *   `path`        — project root
 *   `layers_path` — path to layers.toml (C string, may be null for defaults)
 *
 * Response shape:
 * ```json
 * {
 *   "ok": true,
 *   "data": {
 *     "violations": [
 *       {
 *         "sourcePath": "src/ui/button.ts",
 *         "targetPath": "src/db/model.ts",
 *         "sourceLayer": "ui",
 *         "targetLayer": "db",
 *         "violationType": "skip_call",
 *         "severity": "HIGH"
 *       }
 *     ],
 *     "violationCount": 1
 *   }
 * }
 * ```
 */
char *cartographer_check_layers(const char *path, const char *layers_path);

/**
 * Predict the architectural impact of changing a module.
 *
 * Inputs:
 *   `path`              — project root
 *   `module_id`         — module path (relative to root)
 *   `new_signature`     — optional new signature (may be null)
 *   `remove_signature`  — optional signature to remove (may be null)
 *
 * Response shape:
 * ```json
 * {
 *   "ok": true,
 *   "data": {
 *     "targetModule": "src/auth/user.rs",
 *     "predictedImpact": {
 *       "affectedModules": ["src/api/handler.rs", "src/main.rs"],
 *       "callersCount": 5,
 *       "calleesCount": 2,
 *       "willCreateCycle": false,
 *       "layerViolations": [],
 *       "riskLevel": "MEDIUM",
 *       "healthImpact": -2.0
 *     }
 *   }
 * }
 * ```
 */
char *cartographer_simulate_change(const char *path,
                                   const char *module_id,
                                   const char *new_signature,
                                   const char *remove_signature);

/**
 * Return a compressed skeleton map of the project for LLM context injection.
 *
 * Input:
 *   `path`        — project root
 *   `detail`      — "minimal", "standard", or "extended" (may be null → standard)
 *
 * Response shape:
 * ```json
 * {
 *   "ok": true,
 *   "data": {
 *     "files": [
 *       {
 *         "path": "src/auth/user.rs",
 *         "imports": ["std::collections::HashMap"],
 *         "signatures": ["pub fn authenticate(...) -> User"]
 *       }
 *     ],
 *     "totalFiles": 150,
 *     "totalSignatures": 2300,
 *     "estimatedTokens": 4500
 *   }
 * }
 * ```
 */
char *cartographer_skeleton_map(const char *path, const char *detail);

/**
 * Get skeleton context for a single module with optional dependency depth.
 *
 * Inputs:
 *   `path`      — project root
 *   `module_id` — relative file path
 *   `depth`     — dependency traversal depth (0 = none)
 *
 * Response shape:
 * ```json
 * {
 *   "ok": true,
 *   "data": {
 *     "module": { "path": "...", "imports": [...], "signatures": [...] },
 *     "dependencies": [
 *       { "moduleId": "...", "path": "...", "signatureCount": 12 }
 *     ]
 *   }
 * }
 * ```
 */
char *cartographer_module_context(const char *path, const char *module_id, uint32_t depth);

/**
 * Return the Cartographer library version string (e.g. "9.0.0").
 *
 * Output: raw C string — must be freed with `cartographer_free_string`.
 */
char *cartographer_version(void);

/**
 * Return per-file commit counts over the last `limit` commits.
 *
 * Inputs:
 *   `path`  — project root (C string)
 *   `limit` — number of commits to analyse (0 → 500)
 *
 * Response shape:
 * ```json
 * {
 *   "ok": true,
 *   "data": {
 *     "src/api.rs": 42,
 *     "src/main.rs": 18
 *   }
 * }
 * ```
 * Returns an empty object when the directory is not a git repo.
 */
char *cartographer_git_churn(const char *path, uint32_t limit);

/**
 * Return temporally coupled file pairs from the last `limit` commits.
 *
 * Inputs:
 *   `path`      — project root (C string)
 *   `limit`     — number of commits to analyse (0 → 500)
 *   `min_count` — minimum co-change count to include (0 → 2)
 *
 * Response shape:
 * ```json
 * {
 *   "ok": true,
 *   "data": [
 *     {
 *       "fileA": "src/api.rs",
 *       "fileB": "src/main.rs",
 *       "count": 12,
 *       "couplingScore": 0.92
 *     }
 *   ]
 * }
 * ```
 * Returns an empty array when the directory is not a git repo.
 */
char *cartographer_git_cochange(const char *path, uint32_t limit, uint32_t min_count);

/**
 * Return a function-level diff between two commits.
 *
 * Inputs:
 *   `path`    — project root (C string)
 *   `commit1` — base commit (C string)
 *   `commit2` — target commit (C string; use "HEAD" for latest)
 *
 * Response shape:
 * ```json
 * {
 *   "ok": true,
 *   "data": [
 *     {
 *       "path": "src/api.rs",
 *       "status": "modified",
 *       "added": ["pub fn new_handler(...)"],
 *       "removed": ["fn old_helper(...)"]
 *     },
 *     {
 *       "path": "src/old.rs",
 *       "status": "deleted",
 *       "added": [],
 *       "removed": ["pub fn foo()", "pub fn bar()"]
 *     }
 *   ]
 * }
 * ```
 */
char *cartographer_semidiff(const char *path, const char *commit1, const char *commit2);

/**
 * Return file pairs that co-change frequently but have NO import edge between
 * them — i.e. implicit/hidden coupling that is invisible in the static graph.
 *
 * Inputs:
 *   `path`      — project root
 *   `limit`     — commits to analyse (0 → 500)
 *   `min_count` — minimum co-change count to include (0 → 2)
 *
 * Response shape: same as `cartographer_git_cochange` (array of CoChangePair).
 * Returns an empty array when the directory is not a git repo.
 */
char *cartographer_hidden_coupling(const char *path, uint32_t limit, uint32_t min_count);

/**
 * Return a token-budget-aware ranked skeleton using personalized PageRank.
 *
 * Inputs:
 *   `path`       — project root (C string)
 *   `focus_json` — JSON array of focus file paths for personalization (C string, may be null/empty)
 *   `budget`     — max tokens to include (0 = unlimited)
 *
 * Response shape:
 * ```json
 * {
 *   "ok": true,
 *   "data": [
 *     {
 *       "path": "src/api.rs",
 *       "moduleId": "src/api.rs",
 *       "rank": 0.0842,
 *       "signatureCount": 45,
 *       "estimatedTokens": 680,
 *       "role": "core",
 *       "signatures": ["pub fn rebuild_graph(...) -> ...", "..."]
 *     }
 *   ]
 * }
 * ```
 */
char *cartographer_ranked_skeleton(const char *path,
                                   const char *focus_json,
                                   uint32_t budget);

/**
 * Return public symbols that appear unreferenced across the project (heuristic).
 *
 * Input:  `path` — project root (C string)
 *
 * Response shape:
 * ```json
 * {
 *   "ok": true,
 *   "data": {
 *     "totalCount": 12,
 *     "files": [
 *       {
 *         "path": "src/utils.rs",
 *         "symbols": ["pub fn unused_helper(...)", "pub const OLD_VALUE: ..."]
 *       }
 *     ]
 *   }
 * }
 * ```
 */
char *cartographer_unreferenced_symbols(const char *path);

/**
 * Search for text or regex patterns across all project files.
 *
 * Inputs:
 *   `path`      — project root (C string)
 *   `pattern`   — search pattern (C string; regex unless `literal` is set in opts)
 *   `opts_json` — JSON-encoded search options (may be null → defaults)
 *
 * Options JSON shape:
 * ```json
 * {
 *   "literal":       false,
 *   "caseSensitive": true,
 *   "contextLines":  0,
 *   "maxResults":    100,
 *   "fileGlob":      "*.rs"
 * }
 * ```
 *
 * Response shape:
 * ```json
 * {
 *   "ok": true,
 *   "data": {
 *     "matches": [
 *       {
 *         "path": "src/api.rs",
 *         "lineNumber": 42,
 *         "line": "pub fn rebuild_graph(&self) -> Result<...",
 *         "beforeContext": [{"lineNumber": 40, "line": "// comment"}, ...],
 *         "afterContext":  [{"lineNumber": 43, "line": "    let g = Graph::new();"}, ...]
 *       }
 *     ],
 *     "totalMatches": 1,
 *     "filesSearched": 18,
 *     "truncated": false
 *   }
 * }
 * ```
 */
char *cartographer_search_content(const char *path, const char *pattern, const char *opts_json);

/**
 * Find files matching a glob pattern across the project.
 *
 * Parameters:
 * - `path`      – absolute path to repo root (UTF-8 C string)
 * - `pattern`   – glob pattern, e.g. `"*.rs"` or `"src/**/*.go"` (C string)
 * - `limit`     – max files to return; 0 = unlimited
 * - `opts_json` – optional JSON `FindOptions` or null for defaults:
 *   `{ modifiedSinceSecs, newerThan, minSizeBytes, maxSizeBytes, maxDepth, noIgnore }`
 *
 * Returns a JSON envelope:
 * ```json
 * { "ok": true, "data": { "files": [...], "totalMatches": N, "truncated": false } }
 * ```
 */
char *cartographer_find_files(const char *path,
                              const char *pattern,
                              uint32_t limit,
                              const char *opts_json);

/**
 * Get files/modules directly impacted by changing a target module.
 *
 * Inputs:
 *   `path`        — project root (C string)
 *   `target`      — module ID or path fragment (C string)
 *   `max_related` — cap on returned entries (0 → 10)
 *
 * Response shape:
 * ```json
 * {
 *   "ok": true,
 *   "data": {
 *     "target": "src/api.rs",
 *     "moduleId": "src/api.rs",
 *     "related": [
 *       { "moduleId": "src/main.rs", "path": "src/main.rs", "relationship": "dependent" },
 *       { "moduleId": "src/lib.rs",  "path": "src/lib.rs",  "relationship": "dependency" }
 *     ]
 *   }
 * }
 * ```
 */
char *cartographer_blast_radius(const char *path, const char *target, uint32_t max_related);

/**
 * Return architecture health and debt indicators for a project.
 *
 * Inputs:
 *   `path` — project root (C string)
 *   `days` — look-back window in days (0 → default 30)
 *
 * Response shape:
 * ```json
 * {
 *   "ok": true,
 *   "data": {
 *     "snapshots": [{ "timestamp": ..., "healthScore": 72.5, ... }],
 *     "healthTrend": "At Risk",
 *     "debtIndicators": ["2 dependency cycles detected"],
 *     "recommendations": ["Resolve dependency cycles to improve health score"]
 *   }
 * }
 * ```
 */
char *cartographer_evolution(const char *path, uint32_t days);

/**
 * Return project files modified since a given epoch-millisecond timestamp.
 *
 * Inputs:
 *   `path`     — project root (C string)
 *   `since_ms` — epoch milliseconds; 0 → last 60 seconds
 *
 * Response shape:
 * ```json
 * {
 *   "ok": true,
 *   "data": {
 *     "changedFiles": ["src/api.rs", "src/main.rs"],
 *     "checkedAtMs": 1712345678901
 *   }
 * }
 * ```
 */
char *cartographer_poll_changes(const char *path, uint64_t since_ms);

#endif  /* CARTOGRAPHER_H */
